### PR TITLE
docs(driver): add some note for java and go driver

### PR DESCRIPTION
**Pull request by PsiACE**

### CODE REVIEW

**Review by everpcpc — APPROVED** [review]

**Review by hantmac — APPROVED** [review]
LGTM!

**Comment by BohuTANG** [comment]
Conflicting files
docs/developer/00-drivers/01-python.md

**Comment by BohuTANG** [comment]
Why add the chinese part in this PR?

**Comment by PsiACE** [comment]
> Why update the chinese part in this PR?

So I don't have to wait for gpt to translate. Incremental translation is still a painful task while ensuring quality and stability.

I will try to adjust the translation strategy today.

**Pull request merged**
