### PR TITLE
docs: new CSV options

### PR DESCRIPTION
**Pull request by soyeric128**
- EMPTY_FIELD_AS
- OUTPUT_HEADER
- BINARY_FORMAT

### CODE REVIEW

**Comment by youngsofun** [comment]
@soyeric128 
wait a moment, I will make a little change about related code soon.

**Comment by youngsofun** [comment]
@soyeric128  waiting for https://github.com/datafuselabs/databend/pull/14335 to be reviewed.

**Comment by soyeric128** [comment]
> @soyeric128 waiting for [datafuselabs/databend#14335](https://github.com/datafuselabs/databend/pull/14335) to be reviewed.

Updated and ready for your review.

**Comment by soyeric128** [comment]
I just added BINARY_FORMAT and OUTPUT_HEADER to this PR. Please review them together with EMPTY_FIELD_AS. Thanks. @youngsofun

**Review by youngsofun — APPROVED** [review]

**Pull request merged**
